# Generated by Django 4.2.9 on 2024-01-18 10:45

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonIndex",
            fields=[
                ("id", models.UUIDField(primary_key=True, editable=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TOPIC", "topic"),
                            ("FORUM", "forum"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(editable=False, max_length=255)),
                ("content", models.TextField(blank=True, editable=False)),
                ("content_ts", django.contrib.postgres.search.SearchVectorField(blank=True, editable=False)),
                ("forum_id", models.PositiveBigIntegerField(editable=False)),
                ("forum_slug", models.CharField(editable=False, max_length=255)),
                ("forum_updated", models.DateTimeField(editable=False)),
                ("topic_id", models.PositiveBigIntegerField(editable=False)),
                ("topic_slug", models.CharField(editable=False, max_length=255)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
