# Generated by Django 5.0.8 on 2024-09-05 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = []
