# Generated by Django 6.0.6 on 2026-06-25 08:56

import uuid

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_remove_kind_in_materialized_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP MATERIALIZED VIEW IF EXISTS search_commonindex;",
        ),
        migrations.DeleteModel(
            name="CommonIndex",
        ),
        migrations.CreateModel(
            name="CommonIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(editable=False)),
                ("content", models.TextField(editable=False)),
                ("content_ts", django.contrib.postgres.search.SearchVectorField(editable=False)),
                ("category_slug", models.CharField(editable=False)),
                ("card_slug", models.CharField(editable=False)),
            ],
        ),
    ]
