[project]
name = "lacommunaute"
version = "2.24.0"
description = "La communauté de l'inclusion"
authors = []
license = {text = "ETALAB 2.0"}
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "Django<6.1",
    "python-dotenv",
    "psycopg",
    "django-compressor",
    "django-libsass",
    "sentry-sdk",
    "django-social-share",
    "django-htmx",
    "django-permissions-policy",
    "itoutils[django]",
    "python-frontmatter",
    "markdown",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "pytest-django",
    "pytest-xdist",
    "ruff",
    "djlint",
    "syrupy",
    "beautifulsoup4",
]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = []
# see prefixes in https://beta.ruff.rs/docs/rules/
select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["lacommunaute"]
lines-after-imports = 2

[tool.djlint]
profile="django"
ignore="T002,T003,T027,H006,H023,D018"
max_attribute_length=200
format_css = true
format_js = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["tests*.py", "test_*.py"]
addopts = [
    "--reuse-db",
    "--strict-markers",
]

[tool.pytest.ini_options.markers]
no_django_db = "mark tests that should not be marked with django_db."
