# Generated by Django 5.2.8 on 2026-01-21 20:57

from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email__startswith="email-anonymise-").update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_emaillastseen_missyou_at"),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
