# Generated by Django 5.1.6 on 2025-03-13 14:22
from django.db import migrations
from machina.core.loading import get_class

from lacommunaute.forum_permission.models import ForumPermission, GroupForumPermission, UserForumPermission


PermissionConfig = get_class("forum_permission.defaults", "PermissionConfig")


def drop_permissions(apps, schema_editor):
    UserForumPermission.objects.all().delete()
    GroupForumPermission.objects.all().delete()


def create_permissions(apps, schema_editor):
    """Creates all the permissions from the permission configuration."""
    for config in PermissionConfig.permissions:
        ForumPermission.objects.get_or_create(codename=config["codename"])


def setup_global_permissions(apps, schema_editor):
    authorized_perms = [
        "can_see_forum",
        "can_read_forum",
        "can_start_new_topics",
        "can_reply_to_topics",
        "can_edit_own_posts",
        "can_delete_own_posts",
        "can_post_without_approval",
        "can_download_file",
    ]

    anonymous_perms = [
        UserForumPermission(
            anonymous_user=True,
            authenticated_user=False,
            permission=permission,
            has_perm=permission.codename in authorized_perms,
            forum=None,
        )
        for permission in ForumPermission.objects.all()
    ]

    authentified_perms = [
        UserForumPermission(
            anonymous_user=False,
            authenticated_user=True,
            permission=permission,
            has_perm=permission.codename in authorized_perms,
            forum=None,
        )
        for permission in ForumPermission.objects.all()
    ]
    UserForumPermission.objects.bulk_create(anonymous_perms + authentified_perms)


class Migration(migrations.Migration):
    dependencies = [
        ("forum_permission", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(drop_permissions),
        migrations.RunPython(create_permissions),
        migrations.RunPython(setup_global_permissions),
    ]
