# Generated by Django 6.0.2 on 2026-03-20 10:46

from django.db import migrations


def block_post_permission(apps, schema_editor):
    UserForumPermission = apps.get_model("forum_permission", "UserForumPermission")
    UserForumPermission.objects.filter(permission__codename__in=["can_edit_own_posts", "can_reply_to_topics"]).update(
        has_perm=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("forum_permission", "0002_perms_update"),
    ]

    operations = [
        migrations.RunPython(block_post_permission, reverse_code=migrations.RunPython.noop),
    ]
