# Generated by Django 5.2.10 on 2026-01-23 14:32
from django.db import migrations, models
from django.db.models.query_utils import Q

import lacommunaute.forum_member.models


def remove_invalid_linkedin_profiles(apps, schema_editor):
    ForumProfile = apps.get_model("forum_member", "ForumProfile")

    ForumProfile.objects.exclude(
        Q(linkedin__isnull=True) | Q(linkedin__startswith="https://www.linkedin.com/")
    ).update(linkedin=None)


class Migration(migrations.Migration):
    dependencies = [
        ("forum_member", "0002_forumprofile_cv_forumprofile_internship_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="linkedin",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[lacommunaute.forum_member.models.validate_linkedin],
                verbose_name="lien vers votre profil LinkedIn",
            ),
        ),
        migrations.RunPython(remove_invalid_linkedin_profiles, elidable=True),
    ]
